# This docker compose file contains just the user code for dagster
# It can be used alongside docker-compose-separated-dagster.yml
# for distributed dagster development or on its own for debugging
# with dagster dev

services:
  dagster_user_code:
    image: dagster_user_code_image
    container_name: dagster_user_code
    restart: always
    environment:
      DAGSTER_CURRENT_IMAGE: "dagster_user_code_image"
    volumes:
      - ./code:/opt/dagster/app/code
    networks:
      - dagster_network
    env_file: ".env"
    ports:
      - "5678:5678" # expose this for debugging
      - "5482:5482" # expose this for the dagster dev web server if ran via dagster dev

  headless:
    # image: chromedp/headless-shell:stable
    # stable after 105 causes "devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.",
    # previous image: chromedp/headless-shell:105.0.5195.127 unclear if we can upgrade since neither seems to work
    # seems like might need to pull this before if on macos since we cant specify platform in docker compose
    #  docker run -it --platform linux/amd64 -p 9222:9222 --rm --entrypoint /bin/bash chromedp/headless-shell:latest
    image: chromedp/headless-shell:latest
    ports:
      - 9222:9222
    environment:
      - SERVICE_PORTS=9222
    networks:
      - headless_gleanerio
      - dagster_network

networks:
  dagster_network:
    external: true
  headless_gleanerio:
    name: headless_gleanerio
    external: true


