FROM python:3.10-slim

# Base requirements
COPY requirements.txt user_code_requirements.txt
RUN pip install -r user_code_requirements.txt

# configs and runtime code
WORKDIR /opt/dagster/app
COPY userCode/ /opt/dagster/app/userCode
COPY dagster.yaml /opt/dagster/app/

# Expose the necessary ports
EXPOSE 4000
# Set the home variable so the code locations are loaded properly
ENV DAGSTER_HOME=/opt/dagster/app

COPY ./Docker/dagster/rclone.sh /opt/dagster/app/rclone.sh
RUN /opt/dagster/app/rclone.sh

COPY ./Docker/dagster/entrypoint.sh /opt/dagster/app/entrypoint.sh

# This needs to be a CMD and not an ENTRYPOINT for some reason; it appears that docker swarm might pass implicit arguments and thus not work if it is an ENTRYPOINT
CMD [ "/opt/dagster/app/entrypoint.sh" ]
