# =================================================================
#
# Authors: Colton Loftus <70598503+C-Loftus@users.noreply.github.com>
#
# Copyright (c) 2025 Lincoln Institute of Land Policy
#
# Licensed under the Apache License 2.0.
#
# =================================================================

# This file specifies how dagster should load user code
load_from:
  # Each entry here corresponds to a service in the docker-compose file that exposes user code.
  - grpc_server:
      host: dagster_user_code
      port: 4000
      location_name: "harvest.geoconnex.us"
