name: "An end-to-end test for te entire Geoconnex Scheduler"
description: "Reusable GitHub Action to run E2E tests for the Dagster build"
# inputs:
  # branch:
  #   description: "Branch of the scheduler repo to test against"
  #   required: false
  #   default: "main"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Launch Docker Stack
      run: python3 main.py local
      shell: bash

    - name: Wait for MinIO
      shell: bash
      run: |
        for i in {1..30}; do
          if curl -fs http://localhost:9001/minio/health/live; then
            echo "MinIO is up!"
            exit 0
          fi
          echo "Waiting for MinIO to be ready..."
          sleep 5
        done
        echo "Failed to connect to MinIO after 30 attempts."
        exit 1

    - name: Run tests that don't require secrets
      shell: bash
      run: python3 main.py test
