# This docker compose file contains just the user code for dagster
# It can be used alongside docker-compose-separated-dagster.yml
# for distributed dagster development or on its own for debugging
# with dagster dev

services:
  dagster_user_code:
    image: dagster_user_code_image
    container_name: dagster_user_code
    restart: always
    environment:
      # this is hard coded since we are building the container locally
      - DAGSTER_CURRENT_IMAGE: "dagster_user_code_image"
      # these are specified here since we want to be able to override them in ci/cd without create an entirely new env file
      - NABU_IMAGE
      - GLEANER_IMAGE
    volumes:
      - ../userCode:/opt/dagster/app/userCode
      # When materialized via the UI, dagster runs the
      # user code inside the webserver container
      # However, if we are just running pytest we need to have direct
      # access to the docker sock inside the user code container
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dagster_network
    env_file: "../.env"

  headless:
    # image: chromedp/headless-shell:stable
    # stable after 105 causes "devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.",
    # previous image: chromedp/headless-shell:105.0.5195.127 unclear if we can upgrade since neither seems to work
    # seems like might need to pull this before if on macos since we cant specify platform in docker compose
    #  docker run -it --platform linux/amd64 -p 9222:9222 --rm --entrypoint /bin/bash chromedp/headless-shell:latest
    image: chromedp/headless-shell:latest
    ports:
      - 9222:9222
    environment:
      - SERVICE_PORTS=9222
    networks:
      - dagster_network

networks:
  dagster_network:
    external: true
    driver: overlay
