FROM python:3.10-slim

# Base requirements
COPY Docker/user_code_requirements.txt user_code_requirements.txt
RUN pip install -r user_code_requirements.txt

# install rclone
RUN apt-get -y update; apt-get -y install curl unzip
COPY Docker/rclone.sh rclone.sh
RUN bash rclone.sh

# Check if we are debugging
ARG DAGSTER_DEBUG
# dependencies needed for dagster dev
RUN if [ "$DAGSTER_DEBUG" = "true" ]; then pip install debugpy dagster-webserver; fi
RUN echo "User code 'DAGSTER_DEBUG' value is: $DAGSTER_DEBUG"

# Pass the build argument as an environment variable
ENV DAGSTER_DEBUG=$DAGSTER_DEBUG

# configs and runtime code
WORKDIR /opt/dagster/app
COPY userCode /opt/dagster/app/userCode
COPY templates /opt/dagster/app/templates

# Expose the necessary ports
EXPOSE 4000
# Set the home variable so the code locations are loaded properly
ENV DAGSTER_HOME=/opt/dagster/app

COPY Docker/entrypoint.sh /opt/dagster/app/entrypoint.sh

# This needs to be a CMD and not an ENTRYPOINT for some reason; it appears that docker swarm might pass implicit arguments and thus not work if it is an ENTRYPOINT
CMD [ "/opt/dagster/app/entrypoint.sh" ]
