# Build both the dagster-webserver and the dagster-daemon. 
# Does not need to have access to any pipeline code.

FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY workspace.yaml /opt/dagster/app/
COPY dagster.yaml /opt/dagster/app/dagster.yaml


WORKDIR $DAGSTER_HOME
