linux:
	curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
	unzip rclone-current-linux-amd64.zip
	mv rclone*/rclone ./rclone.linux
	rm -rf rclone-*-linux-amd64*
	
macos:
	curl -O https://downloads.rclone.org/rclone-current-osx-amd64.zip
	unzip rclone-current-osx-amd64.zip
	mv rclone*/rclone ./rclone.macos
	rm -rf rclone-*-osx-amd64*