# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

FROM khaller/graphdb-free

COPY ./iow-config.ttl /repository.init/iow/config.ttl
COPY ./iowprov-config.ttl /repository.init/iowprov/config.ttl
