# this makefile is solely for generating the qlever index
# for local testing; it isn't ran in the pipeline and is just a helper

index:
	qlever index --overwrite-existing

start:
	qlever start

stop:
	qlever stop

restart:
	qlever stop && qlever start