# =================================================================
#
# Authors: Benjamin Webb <40066515+webb-ben@users.noreply.github.com>
#
# Copyright (c) 2025 Lincoln Institute of Land Policy
#
# Licensed under the Apache License 2.0.
#
# =================================================================

# NOTE: this only tests building, there is no good way to test
# runtime functionality in prod without using pytest
name: Test Prod Build
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-build-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Launch Docker Compose
        run: python3 main.py prod --detach

      - name: Debug Docker Containers
        shell: bash
        run: docker ps -a
