# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

# NOTE: this only tests building, there is no good way to test
# runtime functionality in prod without using pytest
name: Test Prod Build
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-build-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Launch Docker Compose
        run: make prod

      - name: Debug Docker Containers
        shell: bash
        run: docker ps -a
