# =================================================================
#
# Authors: Colton Loftus <70598503+C-Loftus@users.noreply.github.com>
#
# Copyright (c) 2025 Lincoln Institute of Land Policy
#
# Licensed under the Apache License 2.0.
#
# =================================================================

name: E2E Test Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        id: checkout
      - name: Run Reusable E2E Test Action
        uses: ./
        with:
          nabu_image: internetofwater/nabu:latest
          gleaner_image: internetofwater/gleaner:latest
