name: E2E Dagster build

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup-docker-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Run the Python script that handles the build and execution
      - name: Launch Docker Stack
        run: python3 main.py local

      - name: Wait for MinIO
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:9001/minio/health/live; then
              echo "MinIO is up!"
              break
            fi
            echo "Waiting for MinIO to be ready..."
            sleep 5
          done
      

      - name: Run pytest
        run: python3 main.py test
