name: E2E Test Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        id: checkout
      - name: Run Reusable E2E Test Action
        uses: ./.github/actions/e2e-scheduler-test
        with:
          branch: main
