name: E2E Dagster build

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup-docker-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Run the Python script that handles the build and execution
      - name: Launch Docker Stack
        run: python3 main.py local

      # Needs to be done in CI since docker stack does not support conditional waits
      - name: Wait for minio
        run: python3 main.py wait_for minio

      - name: Run pytest
        run: python3 main.py test
