# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: E2E Test Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        id: checkout
      - name: Run Reusable E2E Test Action
        uses: ./
        with:
          nabu_image: internetofwater/nabu:latest

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          name: scheduler-code-coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: internetofwater/scheduler
          fail_ci_if_error: true
