name: E2E Dagster build

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup-docker-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Run the Python script that handles the build and execution
      - name: Launch Docker Stack and run tests
        run: python3 main.py local && python3 main.py wait_for "http://localhost:9001/minio/health/live" && python3 main.py test
