# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

name: Pyright Type Checks

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"

      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
