# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

name: Static Checks (Pyright, Ruff, dg check)

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5

      - name: Install the project
        run: uv sync --all-extras --dev --all-packages --all-groups

      - name: Run type checks
        run: uv run pyright

      - name: Run formatter
        run: uv run ruff check

      - name: Run dagster checks that don't require the docker environment to be setup
        run: uv run dg check yaml
